name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install PDM using Pip
        run: pip install --user requests<=2.29 pdm
      # - uses: pdm-project/setup-pdm@v3
      #   name: Setup PDM
      #   with:
      #     python-version: ${{ matrix.python-version }}  # Version range or exact version of a Python version to use, the same as actions/setup-python
      #     cache: true
      #     # well we use virtualenv here
      #     # prerelease: true     # Allow prerelease versions to be installed
      #     # enable-pep582: true  # Enable PEP 582 package loading globally
      - name: Install dependencies
        run: pdm install -v       # Then you can use pdm in the following steps.
